// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZRLBXZvudWwQmVq2FJvPOFL9OIxdOl78',
    appId: '1:1001050594600:web:38e95b1cc045de2f70c41d',
    messagingSenderId: '1001050594600',
    projectId: 'homeshare-4c93e',
    authDomain: 'homeshare-4c93e.firebaseapp.com',
    storageBucket: 'homeshare-4c93e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZC-ypmLrNWT59491xbXVq2DxruSlZBXw',
    appId: '1:1001050594600:android:381bab671d6bc7eb70c41d',
    messagingSenderId: '1001050594600',
    projectId: 'homeshare-4c93e',
    storageBucket: 'homeshare-4c93e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJJsBjbsrvzKVvJGtjOnbo8fbfqb90ubU',
    appId: '1:1001050594600:ios:a6f43e979d7c07eb70c41d',
    messagingSenderId: '1001050594600',
    projectId: 'homeshare-4c93e',
    storageBucket: 'homeshare-4c93e.firebasestorage.app',
    iosBundleId: 'com.example.buurtleen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJJsBjbsrvzKVvJGtjOnbo8fbfqb90ubU',
    appId: '1:1001050594600:ios:a6f43e979d7c07eb70c41d',
    messagingSenderId: '1001050594600',
    projectId: 'homeshare-4c93e',
    storageBucket: 'homeshare-4c93e.firebasestorage.app',
    iosBundleId: 'com.example.buurtleen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZRLBXZvudWwQmVq2FJvPOFL9OIxdOl78',
    appId: '1:1001050594600:web:6aa3074517b4124d70c41d',
    messagingSenderId: '1001050594600',
    projectId: 'homeshare-4c93e',
    authDomain: 'homeshare-4c93e.firebaseapp.com',
    storageBucket: 'homeshare-4c93e.firebasestorage.app',
  );
}
